#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload
pkill sxhkd &
sxhkd &
picom &
syncthing -no-browser &
emacs --fg-daemon &
xsetroot -solid '#5A8E3A'
pkill polybar &
polybar -c /home/thor/.config/polybar example &
feh --bg-scale /home/thor/.config/herbstluftwm/fuji.jpg

Mod=Mod4   # Use the super key as the main modifier

RED='#E78284'
GREEN='#b8bb26'
YELLOW='#E5C890'
BLUE='#8CAAEE'
MAGENTA='#F4B8E4'
CYAN='#81C8BE'
WHITE='#B5BFE2'
active='#E78284'
inactive='#32302f'
background='#303446'
foreground='#C6D0F5'

# tags

tag_names=( I II III IV V VI VII VIII IX X )
tag_keys=( {1..9} 0 )
hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left or / shift left / \
    chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
hc keybind $Mod-Shift-Down  or / shift down / \
    chain , lock , shift_to_monitor -d , focus_monitor -d , unlock
hc keybind $Mod-Shift-Up    or / shift up / \
    chain , lock , shift_to_monitor -u , focus_monitor -u , unlock
hc keybind $Mod-Shift-Right or / shift right / \
    chain , lock , shift_to_monitor -r , focus_monitor -r , unlock

hc keybind $Mod-Control-space split explode
hc keybind $Mod-Shift-space floating toggle
# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle


# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent


# Frames
hc set frame_border_active_color $WHITE #Focused frame color
hc set frame_border_normal_color $background #Unfocused frame color
hc set frame_border_width 3  #border size

hc set frame_bg_active_color "#00000000" #Fill of focused frame
hc set frame_bg_normal_color "#00000066" #Fill of unfocused frame (needs always show frame)
hc set frame_bg_transparent off #Removes the filler color of frame
hc set frame_transparent_width 2 # What part of the filler color should remain?

hc set frame_active_opacity 100 #Focused frame opacity
hc set frame_normal_opacity 65 # Unfocused frame opacity

hc set frame_border_inner_width 0
hc set always_show_frame on
hc set frame_gap 5

# Clients
hc attr theme.padding_top 2 # Padding at top of window. Effects Window Title
hc attr theme.padding_right 2 #Padding 
hc attr theme.padding_left 2 #Padding 
hc attr theme.padding_bottom 2 #Padding 
hc attr theme.title_font ComicCode Nerd Font:style=Regular
# WIndow and tabs color/border
hc attr theme.border_width 1 # WIndows border 
hc attr theme.active.color $background #Window border color
hc attr theme.normal.color $inactive # Window border color unfocused
hc attr theme.urgent.color $RED

# Window Title
hc attr theme.title_height 15
hc attr theme.title_depth 5
hc attr theme.title_align center
hc attr theme.title_when multiple_tabs
hc attr theme.floating.title_when always

hc attr theme.tiling.title_height 15
hc attr theme.active.color $active
hc attr theme.active.title_color $foreground
hc attr theme.normal.color $background
hc attr theme.normal.title_color $foreground

# Color for the outer frame (This is seen with tabs)
hc attr theme.outer_width 0
hc attr theme.active.outer_color $inactive
hc attr theme.normal.outer_color $RED #changed this one


# TABS
hc attr theme.tab_color $background
hc attr theme.tab_title_color $WHITE


# Color for the inner frame.
hc attr theme.inner_width 10
hc attr theme.normal.inner_width 10
hc attr theme.active.inner_color $active
hc attr theme.normal.inner_color $inactive

# Colors for floating 

hc attr theme.floating.title_height 15
hc attr theme.floating.title_depth 3
hc attr theme.floating.outer_width 0
hc attr theme.floating.normal.outer_color $background
hc attr theme.floating.active.outer_color $background
hc attr theme.floating.border.width 0
hc attr theme.background_color $background

hc attr theme.floating.active.color $active
hc attr theme.floating.normal.color $inactive
hc attr theme.floating.normal.title_color $inactive
hc attr theme.floating.active.title_color $foreground

# Color for the inner frame
hc attr theme.floating.inner_width 0
hc attr theme.floating.active.inner_color "#$color1"
hc attr theme.floating.normal.inner_color "#$color5"

hc set window_gap 3 #Gap between windows
hc set frame_padding 0 # Gapp between windows and frames
hc set smart_window_surroundings off
hc set smart_frame_surroundings off
hc set mouse_recenter_gap 0
hc set hide_covered_windows off

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
hc spawn sh $HOME/.config/polybar/launch.sh
#panel=~/.config/herbstluftwm/panel.sh
#[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
#for monitor in $(hc list_monitors | cut -d: -f1) ; do
    # start it on each monitor
#    "$panel" "$monitor" &
#done
